### ISSUE TITLE
Set up MW using php8 and ProfWiki's repo

### ISSUE THREAD

**Issue by hexmode** [ProfessionalWiki/WikibaseRDF#3]
from Jeroen: Getting https://github.com/ProfessionalWiki/mediawiki-dev to run locally, using MW 37 and PHP 8.0

**Comment by hexmode** [comment]
Was thinking of separate tasks initially, but these should probably be here as sub items:

- [ ] Installing Wikibase Repository
- [ ] Installing Wikibase RDF
- [ ] Running the tests and other checks
- [ ] Add some stub UI elements on entity pages. First steps towards creating the UI described (a little bit) in the requirements

**Comment by hexmode** [comment]
Trying to run tests and getting:
```
$ make phpunit
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Using PHP 8.0.19
[fbb4dff7a5b8fb74d8f754f1] [no req]   Error: Class "Wikibase\Client\Tests\Integration\ChangeModification\RecentChangesModificationTest" not found
Backtrace:
from /var/www/mediawiki/extensions/Wikibase/client/tests/phpunit/integration/includes/ChangeModification/ChangeDeletionNotificationJobTest.php(21)
#0 /var/www/mediawiki/vendor/phpunit/phpunit/src/Util/FileLoader.php(66): include_once()
#1 /var/www/mediawiki/vendor/phpunit/phpunit/src/Util/FileLoader.php(54): PHPUnit\Util\FileLoader::load(string)
#2 /var/www/mediawiki/vendor/phpunit/phpunit/src/Framework/TestSuite.php(383): PHPUnit\Util\FileLoader::checkAndLoad(string)
#3 /var/www/mediawiki/vendor/phpunit/phpunit/src/Framework/TestSuite.php(481): PHPUnit\Framework\TestSuite->addTestFile(string)
#4 /var/www/mediawiki/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php(98): PHPUnit\Framework\TestSuite->addTestFiles(array)
#5 /var/www/mediawiki/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\Runner\BaseTestRunner->getTest(string, string, array)
#6 /var/www/mediawiki/tests/phpunit/phpunit.php(141): PHPUnit\TextUI\Command->run(array, boolean)
#7 /var/www/mediawiki/tests/phpunit/phpunit.php(204): PHPUnitMaintClass->execute()
#8 {main}
make: *** [Makefile:157: phpunit] Error 255
```
even though searching with ag shows:
```
mediawiki/extensions/Wikibase/client/tests/phpunit/integration/includes/ChangeModification/RecentChangesModificationTest.php
17:abstract class RecentChangesModificationTest extends MediaWikiIntegrationTestCase {
```
Looking at autoloading for tests now.

**Comment by hexmode** [comment]
Changing phpunit command to
```
make phpunit targetDir=extension/Wikibase/repo
```
(using the added parameter from this pull request[this pull request](https://github.com/ProfessionalWiki/mediawiki-dev/pull/5) ) allows the tests to run.

**Comment by hexmode** [comment]
One failure, but I think I can ignore it for now:
```
1) Wikibase\Repo\Tests\PidLockTest::testPidLock
Try to get the lock, although some already has it
Failed asserting that true is false.

/var/www/mediawiki/extensions/Wikibase/repo/tests/phpunit/includes/PidLockTest.php:22
```
